resources:
  repositories:
  - repository: azure-devops-tools
    type: github
    endpoint: 'xlent-link-admin'
    name: 'nexus-link/nexus-azure-devops-tools'
    ref: 'refs/heads/master'

trigger:
  branches:
    include:
    - master
    - dev
  paths:
    include:
    - 'src/Misc.Web.Sdk/*'

jobs:
- template: 'templates/netcore/v1/jobs/nuget.yml@azure-devops-tools'
  parameters:
    jobName: 'Misc_Web_Sdk'
    testProjectsPath: '**/test/Misc.Web.Sdk.UnitTests/*.csproj'
    nugetProjectsPath: 'src/Misc.Web.Sdk/*.csproj'
    nuGetFeedType: external
    publishFeedCredentials: 'prd-nexus-nuget-external'
    publishVstsFeed: 'Nexus Libs/nexus-nugets'
