resources:
  repositories:
  - repository: azure-devops-tools
    type: github
    endpoint: 'xlent-link-admin'
    name: 'nexus-link/nexus-azure-devops-tools'
    ref: 'refs/heads/master'

trigger:
  branches:
    include:
    - master
    - dev
  paths:
    include:
    - 'src/WorkflowEngine.Sdk.Abstract/*'

jobs:
- template: 'templates/netcore/v1/jobs/nuget.yml@azure-devops-tools'
  parameters:
    jobName: 'WorkflowEngine_Sdk_Abstract'
    testProjectsPath: ''
    nugetProjectsPath: 'src/WorkflowEngine.Sdk.Abstract/*.csproj'
    publishFeedCredentials: 'prd-nexus-nuget-external'
    publishVstsFeed: 'Nexus Libs/nexus-nugets'