/* 
 * Xlent.Lever.KeyTranslator.Facade
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Nexus.Link.KeyTranslator.Sdk.RestClients.Facade.Models
{
    /// <summary>
    /// TranslateRequest
    /// </summary>
    [DataContract]
    public partial class TranslateRequest :  IEquatable<TranslateRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TranslateRequest" /> class.
        /// </summary>
        /// <param name="SourceInstancePath">SourceInstancePath.</param>
        /// <param name="TargetContextPath">TargetContextPath.</param>
        public TranslateRequest(string SourceInstancePath = default(string), string TargetContextPath = default(string))
        {
            this.SourceInstancePath = SourceInstancePath;
            this.TargetContextPath = TargetContextPath;
        }
        
        /// <summary>
        /// Gets or Sets SourceInstancePath
        /// </summary>
        [DataMember(Name="SourceInstancePath", EmitDefaultValue=false)]
        public string SourceInstancePath { get; set; }
        /// <summary>
        /// Gets or Sets TargetContextPath
        /// </summary>
        [DataMember(Name="TargetContextPath", EmitDefaultValue=false)]
        public string TargetContextPath { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TranslateRequest {\n");
            sb.Append("  SourceInstancePath: ").Append(SourceInstancePath).Append("\n");
            sb.Append("  TargetContextPath: ").Append(TargetContextPath).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as TranslateRequest);
        }

        /// <summary>
        /// Returns true if TranslateRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of TranslateRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TranslateRequest other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.SourceInstancePath == other.SourceInstancePath ||
                    this.SourceInstancePath != null &&
                    this.SourceInstancePath.Equals(other.SourceInstancePath)
                ) && 
                (
                    this.TargetContextPath == other.TargetContextPath ||
                    this.TargetContextPath != null &&
                    this.TargetContextPath.Equals(other.TargetContextPath)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.SourceInstancePath != null)
                    hash = hash * 59 + this.SourceInstancePath.GetHashCode();
                if (this.TargetContextPath != null)
                    hash = hash * 59 + this.TargetContextPath.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
