/* 
 * Xlent.Lever.KeyTranslator.Facade
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Nexus.Link.KeyTranslator.Sdk.RestClients.Facade.Models
{
    /// <summary>
    /// ValueOrLockId
    /// </summary>
    [DataContract]
    public partial class ValueOrLockId :  IEquatable<ValueOrLockId>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ValueOrLockId" /> class.
        /// </summary>
        /// <param name="IsLock">IsLock.</param>
        /// <param name="Value">Value.</param>
        /// <param name="LockId">LockId.</param>
        public ValueOrLockId(bool? IsLock = default(bool?), string Value = default(string), string LockId = default(string))
        {
            this.IsLock = IsLock;
            this.Value = Value;
            this.LockId = LockId;
        }
        
        /// <summary>
        /// Gets or Sets IsLock
        /// </summary>
        [DataMember(Name="IsLock", EmitDefaultValue=false)]
        public bool? IsLock { get; set; }
        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name="Value", EmitDefaultValue=false)]
        public string Value { get; set; }
        /// <summary>
        /// Gets or Sets LockId
        /// </summary>
        [DataMember(Name="LockId", EmitDefaultValue=false)]
        public string LockId { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ValueOrLockId {\n");
            sb.Append("  IsLock: ").Append(IsLock).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  LockId: ").Append(LockId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ValueOrLockId);
        }

        /// <summary>
        /// Returns true if ValueOrLockId instances are equal
        /// </summary>
        /// <param name="other">Instance of ValueOrLockId to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ValueOrLockId other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.IsLock == other.IsLock ||
                    this.IsLock != null &&
                    this.IsLock.Equals(other.IsLock)
                ) && 
                (
                    this.Value == other.Value ||
                    this.Value != null &&
                    this.Value.Equals(other.Value)
                ) && 
                (
                    this.LockId == other.LockId ||
                    this.LockId != null &&
                    this.LockId.Equals(other.LockId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.IsLock != null)
                    hash = hash * 59 + this.IsLock.GetHashCode();
                if (this.Value != null)
                    hash = hash * 59 + this.Value.GetHashCode();
                if (this.LockId != null)
                    hash = hash * 59 + this.LockId.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
