pool:
  name: 'Azure Pipelines'
  vmImage: 'windows-latest'

resources:
  repositories:
  - repository: azure-devops-tools
    type: github
    endpoint: 'xlent-link-admin'
    name: 'nexus-link/nexus-azure-devops-tools'
    ref: 'refs/heads/master'

trigger:
  branches:
    include:
    - master
    - dev
  paths:
    include:
    - 'src/WorkflowEngine.Sdk/*'

jobs:
- template: 'templates/netcore/v1/jobs/nuget.yml@azure-devops-tools'
  parameters:
    jobName: 'WorkflowEngine_Sdk'
    testProjectsPath: '**/test/WorkflowEngine.Sdk.UnitTests/*.csproj'
    nugetProjectsPath: 'src/WorkflowEngine.Sdk/*.csproj'
    publishFeedCredentials: 'prd-nexus-nuget-external'
    publishVstsFeed: 'Nexus Libs/nexus-nugets'
