/* 
 * Xlent.Lever.KeyTranslator.Api.WebApi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Nexus.Link.KeyTranslator.Sdk.RestClients.Api.Models
{
    /// <summary>
    /// Context
    /// </summary>
    [DataContract]
    public class Context :  IEquatable<Context>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Context" /> class.
        /// </summary>
        /// <param name="Id">Id.</param>
        /// <param name="TechnicalName">TechnicalName.</param>
        /// <param name="FriendlyName">FriendlyName.</param>
        /// <param name="IsNewestPreferred">IsNewestPreferred.</param>
        /// <param name="CanCreateInstancesManually">CanCreateInstancesManually.</param>
        /// <param name="CanCreateInstancesAutomatically">CanCreateInstancesAutomatically.</param>
        /// <param name="HasAutomaticInstanceGeneration">HasAutomaticInstanceGeneration.</param>
        /// <param name="GeneratedNumberOfCharacters">GeneratedNumberOfCharacters.</param>
        /// <param name="GeneratedAllowedCharacters">GeneratedAllowedCharacters.</param>
        /// <param name="IsCaseSensitive">IsCaseSensitive.</param>
        public Context(Guid? Id = default, string TechnicalName = default, string FriendlyName = default, bool? IsNewestPreferred = default, bool? CanCreateInstancesManually = default, bool? CanCreateInstancesAutomatically = default, bool? HasAutomaticInstanceGeneration = default, int? GeneratedNumberOfCharacters = default, string GeneratedAllowedCharacters = default, bool? IsCaseSensitive = default)
        {
            this.Id = Id;
            this.TechnicalName = TechnicalName;
            this.FriendlyName = FriendlyName;
            this.IsNewestPreferred = IsNewestPreferred;
            this.CanCreateInstancesManually = CanCreateInstancesManually;
            this.CanCreateInstancesAutomatically = CanCreateInstancesAutomatically;
            this.HasAutomaticInstanceGeneration = HasAutomaticInstanceGeneration;
            this.GeneratedNumberOfCharacters = GeneratedNumberOfCharacters;
            this.GeneratedAllowedCharacters = GeneratedAllowedCharacters;
            this.IsCaseSensitive = IsCaseSensitive;
        }
        
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="Id", EmitDefaultValue=false)]
        public Guid? Id { get; set; }
        /// <summary>
        /// Gets or Sets TechnicalName
        /// </summary>
        [DataMember(Name="TechnicalName", EmitDefaultValue=false)]
        public string TechnicalName { get; set; }
        /// <summary>
        /// Gets or Sets FriendlyName
        /// </summary>
        [DataMember(Name="FriendlyName", EmitDefaultValue=false)]
        public string FriendlyName { get; set; }
        /// <summary>
        /// Gets or Sets IsNewestPreferred
        /// </summary>
        [DataMember(Name="IsNewestPreferred", EmitDefaultValue=false)]
        public bool? IsNewestPreferred { get; set; }
        /// <summary>
        /// Gets or Sets CanCreateInstancesManually
        /// </summary>
        [DataMember(Name="CanCreateInstancesManually", EmitDefaultValue=false)]
        public bool? CanCreateInstancesManually { get; set; }
        /// <summary>
        /// Gets or Sets CanCreateInstancesAutomatically
        /// </summary>
        [DataMember(Name="CanCreateInstancesAutomatically", EmitDefaultValue=false)]
        public bool? CanCreateInstancesAutomatically { get; set; }
        /// <summary>
        /// Gets or Sets HasAutomaticInstanceGeneration
        /// </summary>
        [DataMember(Name = "HasAutomaticInstanceGeneration", EmitDefaultValue = false)]
        public bool? HasAutomaticInstanceGeneration { get; set; }
        /// <summary>
        /// Gets or Sets GeneratedNumberOfCharacters
        /// </summary>
        [DataMember(Name = "GeneratedNumberOfCharacters", EmitDefaultValue = false)]
        public int? GeneratedNumberOfCharacters { get; set; }
        /// <summary>
        /// Gets or Sets GeneratedAllowedCharacters
        /// </summary>
        [DataMember(Name = "GeneratedAllowedCharacters", EmitDefaultValue = false)]
        public string GeneratedAllowedCharacters { get; set; }
        /// <summary>
        /// Gets or Sets IsCaseSensitive
        /// </summary>
        [DataMember(Name="IsCaseSensitive", EmitDefaultValue=false)]
        public bool? IsCaseSensitive { get; set; }
        /// <summary>
        /// Gets or Sets VersionTag
        /// </summary>
        [DataMember(Name="VersionTag", EmitDefaultValue=false)]
        public Guid? VersionTag { get; private set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Context {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  TechnicalName: ").Append(TechnicalName).Append("\n");
            sb.Append("  FriendlyName: ").Append(FriendlyName).Append("\n");
            sb.Append("  IsNewestPreferred: ").Append(IsNewestPreferred).Append("\n");
            sb.Append("  CanCreateInstancesManually: ").Append(CanCreateInstancesManually).Append("\n");
            sb.Append("  CanCreateInstancesAutomatically: ").Append(CanCreateInstancesAutomatically).Append("\n");
            sb.Append("  HasAutomaticInstanceGeneration: ").Append(HasAutomaticInstanceGeneration).Append("\n");
            sb.Append("  GeneratedNumberOfCharacters: ").Append(GeneratedNumberOfCharacters).Append("\n");
            sb.Append("  GeneratedAllowedCharacters: ").Append(GeneratedAllowedCharacters).Append("\n");
            sb.Append("  IsCaseSensitive: ").Append(IsCaseSensitive).Append("\n");
            sb.Append("  VersionTag: ").Append(VersionTag).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return Equals(obj as Context);
        }

        /// <summary>
        /// Returns true if Context instances are equal
        /// </summary>
        /// <param name="other">Instance of Context to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Context other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    Id == other.Id ||
                    Id != null &&
                    Id.Equals(other.Id)
                ) && 
                (
                    TechnicalName == other.TechnicalName ||
                    TechnicalName != null &&
                    TechnicalName.Equals(other.TechnicalName)
                ) && 
                (
                    FriendlyName == other.FriendlyName ||
                    FriendlyName != null &&
                    FriendlyName.Equals(other.FriendlyName)
                ) && 
                (
                    IsNewestPreferred == other.IsNewestPreferred ||
                    IsNewestPreferred != null &&
                    IsNewestPreferred.Equals(other.IsNewestPreferred)
                ) && 
                (
                    CanCreateInstancesManually == other.CanCreateInstancesManually ||
                    CanCreateInstancesManually != null &&
                    CanCreateInstancesManually.Equals(other.CanCreateInstancesManually)
                ) && 
                (
                    CanCreateInstancesAutomatically == other.CanCreateInstancesAutomatically ||
                    CanCreateInstancesAutomatically != null &&
                    CanCreateInstancesAutomatically.Equals(other.CanCreateInstancesAutomatically)
                ) &&
                (
                    HasAutomaticInstanceGeneration == other.HasAutomaticInstanceGeneration ||
                    HasAutomaticInstanceGeneration != null &&
                    HasAutomaticInstanceGeneration.Equals(other.HasAutomaticInstanceGeneration)
                ) &&
                (
                    GeneratedNumberOfCharacters == other.GeneratedNumberOfCharacters ||
                    GeneratedNumberOfCharacters != null &&
                    GeneratedNumberOfCharacters.Equals(other.GeneratedNumberOfCharacters)
                ) &&
                (
                    GeneratedAllowedCharacters == other.GeneratedAllowedCharacters ||
                    GeneratedAllowedCharacters != null &&
                    GeneratedAllowedCharacters.Equals(other.GeneratedAllowedCharacters)
                ) &&
                (
                    IsCaseSensitive == other.IsCaseSensitive ||
                    IsCaseSensitive != null &&
                    IsCaseSensitive.Equals(other.IsCaseSensitive)
                ) && 
                (
                    VersionTag == other.VersionTag ||
                    VersionTag != null &&
                    VersionTag.Equals(other.VersionTag)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                var hash = 41;
                // Suitable nullity checks etc, of course :)
                if (Id != null)
                    hash = hash * 59 + Id.GetHashCode();
                if (TechnicalName != null)
                    hash = hash * 59 + TechnicalName.GetHashCode();
                if (FriendlyName != null)
                    hash = hash * 59 + FriendlyName.GetHashCode();
                if (IsNewestPreferred != null)
                    hash = hash * 59 + IsNewestPreferred.GetHashCode();
                if (CanCreateInstancesManually != null)
                    hash = hash * 59 + CanCreateInstancesManually.GetHashCode();
                if (CanCreateInstancesAutomatically != null)
                    hash = hash * 59 + CanCreateInstancesAutomatically.GetHashCode();
                if (HasAutomaticInstanceGeneration != null)
                    hash = hash * 59 + HasAutomaticInstanceGeneration.GetHashCode();
                if (GeneratedNumberOfCharacters != null)
                    hash = hash * 59 + GeneratedNumberOfCharacters.GetHashCode();
                if (GeneratedAllowedCharacters != null)
                    hash = hash * 59 + GeneratedAllowedCharacters.GetHashCode();
                if (IsCaseSensitive != null)
                    hash = hash * 59 + IsCaseSensitive.GetHashCode();
                if (VersionTag != null)
                    hash = hash * 59 + VersionTag.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
