resources:
  repositories:
  - repository: azure-devops-tools
    type: github
    endpoint: 'xlent-link-admin'
    name: 'nexus-link/nexus-azure-devops-tools'
    ref: 'refs/heads/master'
 
trigger:
  branches:
    include:
    - master
    - dev
    - features/*
  paths:
    include:
    - 'src/Commands.Sdk/*'   
    
jobs:
- template: 'templates/netcore/v1/jobs/nuget.yml@azure-devops-tools'
  parameters:
    jobName: 'CommandsSdk'
    testProjectsPath: ''
    nugetProjectsPath: '**/src/Commands.Sdk/*.csproj'
    nuGetFeedType: external
    publishFeedCredentials: 'prd-nexus-nuget-external'
